services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m app.main
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - valkey
    volumes:
      - uploads_data:/mnt/uploads

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run app/streamlit_app.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - FASTAPI_URL=http://api:8000
    depends_on:
      - api

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: rq worker --url redis://valkey:6379
    env_file:
      - .env
    depends_on:
      - mongo
      - valkey
    volumes:
      - uploads_data:/mnt/uploads

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

  valkey:
    image: valkey/valkey:latest
    restart: always
    volumes:
      - valkey_data:/data

volumes:
  mongodb_data:
  valkey_data:
  uploads_data: